### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by ghostcow** [kan-bayashi/PytorchWaveNetVocoder#23]
In [feature_extract.py lines 241-242](https://github.com/kan-bayashi/PytorchWaveNetVocoder/blob/master/src/bin/feature_extract.py#L241-L242) `/feat` holds the extended features (upsampled features), and `/feat_org` holds the original features.

On the other hand, [decode.py lines 74-77](https://github.com/kan-bayashi/PytorchWaveNetVocoder/blob/master/src/bin/decode.py#L74-L77), `/feat` is loaded from the features file when `upsampling_factor == 0`, and `/feat_org` is loaded otherwise.

Shouldn't it be the other way around?

Thanks

**Comment by kan-bayashi** [comment]
`upsampling_factor==0` represents that we do not additional use upsampling layer. 
In other words, when we set `upsampling_factor=0`, instead of the use of extended features (`/feat`), we use `UpSampling` layer with original features (`/feat_org`).
Therefore, in decoding, if `upsampling_factor = 0`, `/feat_org` is loaded.

Sorry for my misleading script.

**Comment by ghostcow** [comment]
Thanks
